### ISSUE TITLE
Can't find out .pickle files

### ISSUE THREAD

**Issue by FanKuan44** [SamsungLabs/nb-asr#1]
Hi guys, I can't find out .pickle files. Can you guys show me where I can find them? Thank you guys.

**Comment by vaenyr** [comment]
Here you are:
https://github.com/SamsungLabs/nb-asr/releases/tag/v1.0.0
for the reference, you need to go to the "Releases" page. :)
![image](https://user-images.githubusercontent.com/274654/117134624-b4386e80-ad9d-11eb-95f0-1394e5116c09.png)

Feel free to reopen the issue if for some reason you are still unable to obtain the files!
