### ISSUE TITLE
Does the data-set have FLOPs?

### ISSUE THREAD

**Issue by akhauriyash** [SamsungLabs/nb-asr#2]
Hello,

Thanks for providing the code to NBASR!  
I have been exploring the dataset, and it is really easy to use, unfortunately I am not able to see the FLOPs in 
```
>>> net_data.full_info(sampled_model) 

{'val_per': [0.8780634, 0.9452082, 0.95351, 0.93564457, 0.8863652, 0.90721923, 0.93982863, 0.91538817, 0.9312612, 0.8334994, 0.8518297, 0.8423325, 0.8491731, 0.84332865, 0.83662087, 0.9412898, 0.9466029, 0.9489274, 0.93684, 0.85807264, 0.8378827, 0.8760045, 0.8589361, 0.84957165, 0.8576078, 0.8619911, 0.867105, 0.8592681, 0.86052996, 0.8487082, 0.8488411, 0.8546191, 0.90954375, 0.8727502, 0.88218105, 0.86557746, 0.8830444, 0.8641164, 0.8586704, 0.8488411], 'test_per': 0.8325710296630859, 'arch_vec': [(1, 0), (0, 1, 0), (0, 1, 1, 1)], 'model_hash': '1b219cc8f41f6c818e59d1694a354d41', 'seed': 1234, 'gtx-1080ti-fp32': {'latency': 0.031280517578125}, 'jetson-nano-fp32': {'latency': 0.5050671100616455}}
```
I think the paper mentioned having FLOPs as well, so just thought I'd confirm :)

**Comment by vaenyr** [comment]
Hi! Thanks for the interest in our work, I hope you find the dataset useful. :)
I've double checked and FLOPs are indeed missing from the current files - thanks for bringing that to your attention!
We will add them as soon as possible (worst case scenario we'll have to recompute them, if the raw material got lost, but that shouldn't take too long anyway).

Cheers

**Comment by akhauriyash** [comment]
Hello,

Thanks for the quick response. I do find the work very useful, very easy to use as well :) 
Looking forward for the patch.

**Comment by AbhinavMehrotra** [comment]
Hi, this issue is resolved and now the dataset contains flops.
